#!/usr/bin/env python3
"""Generate portable LuaJIT declarations from pinned Ghostty headers."""

import pathlib
import configparser
import re
import subprocess
import sys
import tempfile
import textwrap

if len(sys.argv) > 1:
    source = pathlib.Path(sys.argv[1])
else:
    wrap = configparser.ConfigParser()
    wrap.read("subprojects/ghostty.wrap")
    source = pathlib.Path("subprojects") / wrap["wrap-file"]["directory"]
target = pathlib.Path("plugins/ghostty/ffi_defs.lua")
with tempfile.TemporaryDirectory() as tmp:
    include = pathlib.Path(tmp)
    # LuaJIT provides these standard types. Avoid embedding host libc typedefs.
    for name in ("stdint.h", "stddef.h", "stdbool.h"):
        (include / name).write_text("")
    (include / "limits.h").write_text("#define INT_MAX 2147483647\n")
    declarations = subprocess.check_output(
        [
            "cc",
            "-std=c11",
            "-E",
            "-P",
            "-DGHOSTTY_STATIC",
            "-nostdinc",
            "-I" + tmp,
            "-I" + str(source / "include"),
            "-x",
            "c",
            "-",
        ],
        input=b"#include <ghostty/vt.h>\n",
    ).decode()
declarations = re.sub(r"\n\s*\n", "\n", declarations)
declarations = re.sub(r"static inline [^{]+\{[^}]*\}\n", "", declarations)
# LuaJIT uses C enums; the INT_MAX sentinels retain the required int layout.
declarations = re.sub(r"\benum\s*:\s*int\b", "enum", declarations)
# GCC and Clang leave different padding where GHOSTTY_API was expanded.
declarations = re.sub(
    r"^[ \t]+(?=(?:const\s+)?\w+[ *]*ghostty_)", "", declarations, flags=re.M
)
# Wrap at whitespace without changing C tokens or requiring another build tool.
declarations = (
    "\n".join(
        (
            textwrap.fill(
                line,
                width=80,
                subsequent_indent=re.match(r"\s*", line).group() + "  ",
                break_long_words=False,
                break_on_hyphens=False,
            )
            if len(line) > 80
            else line
        )
        for line in declarations.splitlines()
    )
    + "\n"
)
target.write_text(
    "-- Generated by scripts/generate-ffi.py; do not edit by hand.\n"
    "-- Ghostty 12752b2ac1bb05ce53402ed8c853ed1f96eef0b1 (MIT).\n"
    "-- See LICENSE.ghostty in this directory.\n"
    'local ffi = require "ffi"\n\n'
    "ffi.cdef [[\n" + declarations + "]]\n"
)
